### ISSUE TITLE
It seams the newly pushed MicroOS image is corrupted

### ISSUE THREAD

**Issue by arashmhashemi** [kube-hetzner/terraform-hcloud-kube-hetzner#389] opened 2022-11-02 21:43 UTC
OpenSUSE has pushed an upgrade yesterday on Nov 1st, which seems to be corrupted:

```
Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
2849c3|OK  |        n/a|/root/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2.meta4
7a0476|OK  |   187MiB/s|/root/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2

...

qemu-img: error while reading at byte 1032781824: Input/output error
qemu-img: error while reading at byte 1032847360: Input/output error

│ Error: remote-exec provisioner error
│ 
│   with module.kube-hetzner.module.agents["1-0-agent-cpx21"].hcloud_server.server,
│   on .terraform/modules/kube-hetzner/modules/host/main.tf line 64, in resource "hcloud_server" "server":
│   64:   provisioner "remote-exec" {
│ 
│ error executing "/tmp/terraform_1411677936.sh": Process exited with status 1
```

**Comment by fischerman** [comment] 2022-11-03 09:56
Duplicate of https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/360?

**Comment by mysticaltech** [comment] 2022-11-03 13:52
Yes, it could be due to the fact that somehow aria2c no longer works, I will switch to wget later today.

**Comment by mysticaltech** [comment] 2022-11-03 15:08
Closing as a duplicate.

**Closed by mysticaltech** 2022-11-03 15:08 UTC
