### ISSUE TITLE
open /host/proc/1/mounts: permission denied

### ISSUE THREAD

**Issue by ron137** [kube-hetzner/terraform-hcloud-kube-hetzner#739] opened 2023-04-20 09:20 UTC
### Description

I get "open /host/proc/1/mounts: permission denied" after I updated the module to the last one

### Kube.tf file

I created new cluster and I noticed I don't see any data of the disk on grafana, then I checked the logs of prometheus and I found this error after I updated the module to the last one: 

```terraform
ts=2023-04-20T09:11:29.262Z caller=collector.go:169 level=error msg="collector failed" name=filesystem duration_seconds=0.007330841 err="open /host/proc/1/mounts: permission denied" 
```

It worked in previous versions

### Platform

Mac

**Comment by mysticaltech** [comment] 2023-04-20 11:58
@ron137 FYI https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/697

**Comment by mysticaltech** [comment] 2023-04-21 05:41
@ron137 Please don't hesitate to submit a PR with your SELinux required permissions, or tag me with your data in the issue above for me to integrate them ASAP. Closing it for now as related to the above issue. (Don't forget to tag me).

**Closed by mysticaltech** 2023-04-21 05:41 UTC

**Comment by markthebault** [comment] 2023-06-13 11:36
Hi There, did you found a solution to this problem, I am trying to run node-exporter for monitoring and I have this issue.

**Comment by dstockhammer** [comment] 2023-11-02 07:48
Hi @ron137, did you ever find a solution to this issue? I get the same errors when running Grafana Agent. I tried to resolve the issue via tweaking the SELinux rules, but it looks like SELinux doesn't actually cause the problem... 🤔

**Comment by mysticaltech** [comment] 2023-11-03 16:24
@dstockhammer  Are you 100% positive you were debugging in the correct node? Did you try running the failed command manually? Please continue digging down in the logs, you will find the cause and it's usually caused by SELinux. If not, please open a proper issue with all the details to be able to reproduce.
