### ISSUE TITLE
[Bug]: Packer is crashing while creating x86 snapshot

### ISSUE THREAD

**Issue by Mammut-Felix** [kube-hetzner/terraform-hcloud-kube-hetzner#889] opened 2023-07-17 12:06 UTC
### Description

Packer crashes while building the x86 snapshot.
Arm is running without errors.

`==> hcloud.microos-x86-snapshot: 2023-07-17 12:01:05 (158 MB/s) - ‘openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2’ saved [414580736/414580736]
==> hcloud.microos-x86-snapshot:
==> hcloud.microos-x86-snapshot: Provisioning with shell script: /var/folders/yz/q7cxzgw13b31vxjlq1xdjl9r0000gn/T/packer-shell1191919114
==> hcloud.microos-x86-snapshot: + echo MicroOS image loaded, writing to disk...
    hcloud.microos-x86-snapshot: MicroOS image loaded, writing to disk...
==> hcloud.microos-x86-snapshot: + ls -a
==> hcloud.microos-x86-snapshot: + grep -ie ^opensuse.*microos.*qcow2$
==> hcloud.microos-x86-snapshot: + qemu-img convert -p -f qcow2 -O host_device openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2 /dev/sda
==> hcloud.microos-x86-snapshot: /tmp/script_2705.sh: 4: qemu-img: not found
==> hcloud.microos-x86-snapshot: Provisioning step had errors: Running the cleanup provisioner, if present...
==> hcloud.microos-x86-snapshot: Destroying server...
==> hcloud.microos-x86-snapshot: Deleting temporary ssh key...
Build 'hcloud.microos-x86-snapshot' errored after 1 minute 26 seconds: Script exited with non-zero exit status: 127. Allowed exit codes are: [0]`

### Kube.tf file

```terraform
Not needed
```

### Platform

Mac

**Comment by ifeulner** [comment] 2023-07-18 10:00
Well, "packer crashes" is not really the right term... if I read the logs right, `qemu-img`could not be found anymore, looks like Hetzner changed the image.

**Comment by mysticaltech** [comment] 2023-07-19 04:03
@kube-hetzner/core Can someone reproduce?

**Comment by M4t7e** [comment] 2023-07-19 08:03
I just tested it with the latest version from master branch and it worked fine for me.

@ifeulner I think the image is not provided by Hetzner. The download URL is https://download.opensuse.org/repositories/devel:/kubic:/images/openSUSE_Tumbleweed/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2 and effectively you will be 302 redirected to a mirror that is close to you. See here:
```bash
# wget --timeout=5 --waitretry=5 --tries=5 --retry-connrefused --inet4-only https://download.opensuse.org/repositories/devel:/kubic:/images/openSUSE_Tumbleweed/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2 
--2023-07-19 07:57:32--  https://download.opensuse.org/repositories/devel:/kubic:/images/openSUSE_Tumbleweed/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ftp.gwdg.de/pub/opensuse/repositories/devel%3A/kubic%3A/images/openSUSE_Tumbleweed/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2 [following]
--2023-07-19 07:57:32--  https://ftp.gwdg.de/pub/opensuse/repositories/devel%3A/kubic%3A/images/openSUSE_Tumbleweed/openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2
Resolving ftp.gwdg.de (ftp.gwdg.de)... 134.76.12.6
Connecting to ftp.gwdg.de (ftp.gwdg.de)|134.76.12.6|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 414646272 (395M) [application/octet-stream]
Saving to: ‘openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2’

openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2  100%[=================================================================================================>] 395.44M   225MB/s    in 1.8s    

2023-07-19 07:57:34 (225 MB/s) - ‘openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2’ saved [414646272/414646272]
# ls -a | grep -ie '^opensuse.*microos.*qcow2$'
openSUSE-MicroOS.x86_64-OpenStack-Cloud.qcow2
```

**Comment by ifeulner** [comment] 2023-07-19 08:08
@M4t7e I meant the Hetzner rescue image, this provides the `qemu-img` binary that is used to write the MicroOS image to disk. And that one was not found regarding to the logs provided above.

**Comment by M4t7e** [comment] 2023-07-19 08:24
@ifeulner Yes, I also got it after I posted it and edited my comment immediately... sorry ^^

Here is how my image looks like and now I tested it about 5 times. Still can't reproduce...
```bash
==> hcloud.microos-x86-snapshot: + cat /etc/os-release
    hcloud.microos-x86-snapshot: PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
    hcloud.microos-x86-snapshot: NAME="Debian GNU/Linux"
    hcloud.microos-x86-snapshot: VERSION_ID="12"
    hcloud.microos-x86-snapshot: VERSION="12 (bookworm)"
    hcloud.microos-x86-snapshot: VERSION_CODENAME=bookworm
    hcloud.microos-x86-snapshot: ID=debian
    hcloud.microos-x86-snapshot: HOME_URL="https://www.debian.org/"
    hcloud.microos-x86-snapshot: SUPPORT_URL="https://www.debian.org/support"
    hcloud.microos-x86-snapshot: BUG_REPORT_URL="https://bugs.debian.org/"
==> hcloud.microos-x86-snapshot: + which qemu-img
    hcloud.microos-x86-snapshot: /usr/bin/qemu-img
```

**Comment by mysticaltech** [comment] 2023-07-19 16:16
Great @M4t7e, thanks for the info. It seems fixed then, they must have received complaints.

**Comment by aleksasiriski** [comment] 2023-07-22 09:29
@Mammut-Felix can this be closed?

**Comment by mysticaltech** [comment] 2023-07-22 13:36
@Mammut-Felix @aleksasiriski I just doubled checked and all good, so closing this.

**Closed by mysticaltech** 2023-07-22 13:36 UTC
Labels: bug
