### ISSUE TITLE
system-upgrade-controller bug

### ISSUE THREAD

**Issue by maggie44** [kube-hetzner/terraform-hcloud-kube-hetzner#1110] opened 2023-12-05 16:19 UTC
### Description

My config file is set to: `initial_k3s_channel = "v1.28"`

For some reason it seems to be trying to pull a pre-release instead of the stable latest: https://github.com/k3s-io/k3s/releases

Is there a way to disable pre-releases and still use the v1.28 tag?

<img width="1093" alt="Screenshot 2023-12-05 at 16 11 28" src="https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/assets/64841595/2e845422-5d40-412b-add0-79cd4038b9a1">

### Kube.tf file

```terraform
Kube-hetzner: "2.10.1"
automatically_upgrade_os = true
```

### Platform

OpenSuse

**Comment by jr-dimedis** [comment] 2023-12-05 21:49
@maggie44: at first: can you please add a proper title to this issue? Without that you probably can't expect that anyone looks into it. It was pure luck, that I saw it, because I am currently facing an issue with system-upgrade-controller as well and checked at first if somebody added already an issue for it and clicked on this "empty" bug for curiosity.

I am on K3s channel v1.26 and yesterday v1.26.11 was released.

The update fails in a similar fashion on my clusters. The pod created from the system-upgrade-controller job can't pull the image, and I think that's because the tag misses the "-amd64" suffix. At least do the images exist on the Docker hub with the "-amd" suffix.

```
Failed to pull image "rancher/k3s-upgrade:v1.26.11-k3s1": rpc error: code = NotFound desc = failed to pull
and unpack image "docker.io/rancher/k3s-upgrade:v1.26.11-k3s1": failed to resolve reference
"docker.io/rancher/k3s-upgrade:v1.26.11-k3s1": docker.io/rancher/k3s-upgrade:v1.26.11-k3s1: not found
``` 

I tried to pull the image with this name on my workstation using docker and it fails. But with "-amd64" it works:

```
$ docker pull docker.io/rancher/k3s-upgrade:v1.26.11-k3s1
Error response from daemon: manifest for rancher/k3s-upgrade:v1.26.11-k3s1
not found: manifest unknown: manifest unknown

$ docker pull docker.io/rancher/k3s-upgrade:v1.26.11-k3s1-amd64
v1.26.11-k3s1-amd64: Pulling from rancher/k3s-upgrade
63b65145d645: Pull complete 
3bac5b38ce2f: Pull complete 
46faa50ce4cd: Pull complete 
5b273207fbf8: Pull complete 
Digest: sha256:cd41296483b2042ffa1136430f6c48b883bf1368efd16c567cfef68011566e7f
Status: Downloaded newer image for rancher/k3s-upgrade:v1.26.11-k3s1-amd64
docker.io/rancher/k3s-upgrade:v1.26.11-k3s1-amd64
```

I am pretty sure that's no kube-hetzner issue but probably someone here can help nevertheless :)

**Comment by mysticaltech** [comment] 2023-12-06 01:19
Thanks for finding this bug folks. We rely on https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml but in that file, the version of the system-upgrade controller image has not been updated in a long time. It's v0.11.0 but the latest is [v0.13.2](https://github.com/rancher/system-upgrade-controller/releases/tag/v0.13.2) that was released last week.

So we need to upgrade with our [kustomization](https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/blob/84581b93e7ada29e496d7b02590d6756739fec96/kustomize/system-upgrade-controller.yaml). Also, we need to add a variable to allow specification of the version manually, like what we do for other manifest we deploy.

PRs most welcome, otherwise will fix ASAP.

**Comment by primeXchange** [comment] 2023-12-06 14:19
The issue is known and they're working on it apparently.

https://github.com/k3s-io/k3s/issues/8990

**Comment by aleksasiriski** [comment] 2023-12-07 11:43
I don't think that those "prereleases" are actual prereleases. It's all in the naming scheme. If it contains rc / RC (release candidate) then it should NOT be used, but otherwise it's a release. As it seems, it's the problem with upstream K3s and they are working on fixing it (missing images on dockerhub)

**Comment by janis-ax** [comment] 2023-12-07 14:57
Seems they solved the issue.

**Comment by aleksasiriski** [comment] 2023-12-07 15:29
Closing this as it's been resolved upstream.

**Closed by aleksasiriski** 2023-12-07 15:29 UTC
Labels: bug
