### ISSUE TITLE
[Feature Request]: Add node pool name as a label to nodes

### ISSUE THREAD

**Issue by lpellegr** [kube-hetzner/terraform-hcloud-kube-hetzner#842] opened 2023-06-14 20:28 UTC
Adding node pool name as a label to nodes created by kube-hetzner would allow easy scheduling of pods to nodes that belong to a given node pool by using the simple and standard `nodeSelector` field.

**Comment by mysticaltech** [comment] 2023-07-26 08:28
Closing as a duplicate of #903

**Closed by mysticaltech** 2023-07-26 08:28 UTC
Labels: enhancement
