### ISSUE TITLE
Cluster wide IPv6?

### ISSUE THREAD

**Issue by riemervdzee** [kube-hetzner/terraform-hcloud-kube-hetzner#772] opened 2023-04-29 10:55 UTC
### Description

I'm currently debugging an issue on my cluster where my workloads 'sometimes' cannot access an external website/endpoint. I narrowed this down to ipv4/6 issues; when coredns returns an ipv4 address my services work, if it returns an ipv6 address then opening a socket fails (errors like `Network unreachable`, `ENETUNREACH`). 

When I log into the containers I see no default route for ipv6 and cannot ping via ipv6, the same happens when I log into a controlplane or agent node.

I've tested this with both Cilium and Flannel as CNI's. Is it possible to enable ipv6 somewhere, or configure coredns to use ipv4 only?

### Kube.tf file

```terraform
module "kube-hetzner" {
  providers = {
    hcloud = hcloud
  }
  hcloud_token = var.hcloud_token

  source = "kube-hetzner/kube-hetzner/hcloud"
  version = "2.1.1"

  ssh_port = 2222
  ssh_public_key = file("...")
  ssh_private_key = file("....")

  network_region = "eu-central" # change to `us-east` if location is ash

  control_plane_nodepools = [
    {
      name        = "control-plane-fsn1",
      server_type = "cpx21",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 1
    },
  ]
  agent_nodepools = [
    {
      name        = "agent-lg-nbg1",
      server_type = "cpx21",
      location    = "nbg1",
      labels      = [],
      taints      = [],
      count       = 0
    },
  ]

  cluster_name = "k3s-test"
  restrict_outbound_traffic = false
}

provider "hcloud" {
  token = var.hcloud_token
}

terraform {
  required_version = ">= 1.3.3"
  required_providers {
    hcloud = {
      source  = "hetznercloud/hcloud"
      version = ">= 1.35.2"
    }
  }
}

output "kubeconfig" {
  value     = module.kube-hetzner.kubeconfig
  sensitive = true
}

variable "hcloud_token" {
  sensitive = true
  default   = ""
}
```

### Screenshots

Screenshot when logged in a container

<img width="433" alt="Screenshot 2023-04-29 at 12 49 58" src="https://user-images.githubusercontent.com/510299/235298806-675bb2d9-e5db-4e9f-ab38-3fbcdec1f8c8.png">

Screenshot when logged in from the controlplane node. The same happens on agents
<img width="651" alt="Screenshot 2023-04-29 at 12 32 30" src="https://user-images.githubusercontent.com/510299/235298190-58560bd1-7595-4284-94ee-a2f5daf3af82.png">

### Platform

Mac

**Comment by riemervdzee** [comment] 2023-04-29 10:58
A screenshot of dns queries returning ipv6 addresses, but a ping fails

<img width="499" alt="Screenshot 2023-04-29 at 12 57 31" src="https://user-images.githubusercontent.com/510299/235299068-d1f093c7-fafd-43e1-8219-55d99608ec4d.png">

**Comment by mysticaltech** [comment] 2023-04-29 11:59
@riemervdzee That's an interesting issue. We never added IPv6 support internally, as I'm not sure Hetzner private network supports them, however, not sure if that's even a factor.

Try setting `load_balancer_disable_ipv6` to true in your kube.tf, it should remove support for IPv6. Now if you really want IPv6 support all the way down, PRs are welcome! 

Or just use Cloudflare with their DNS proxy (orange cloud) to do the trick (it does automatic IPv6 to IPv4 conversion I believe).

**Comment by mysticaltech** [comment] 2023-04-29 12:00
@kube-hetzner/core FYI the above, if you have any additional insights!

**Comment by riemervdzee** [comment] 2023-04-29 12:09
@mysticaltech thank you for your quick reply. In the `kube.tf` posted above no load-balancers are created, and `tf plan` does not report any planned changes.

Maybe I was unclear in my previous posts. My issue isn't on the `ingress` side but on the `egress` side of things, the containers inside the cluster cannot connect to external resources via ipv6? 

Spinning up a simple server in Hetzner console results in a server that has ipv6 egress. I will try to determine whether a private network has any effect

**Comment by aleksasiriski** [comment] 2023-04-29 15:24
I'll test this on my cluster and report back..

**Comment by mysticaltech** [comment] 2023-04-30 00:04
@riemervdzee Thanks for the clarification. Egress IPv6 is definitely not something we have had in mind when building this project. PRs are most welcome to fix this!

@aleksasiriski Looking foward for your findings too! 🙏

**Comment by riemervdzee** [comment] 2023-04-30 13:43
So after some digging, I got some progress in getting ipv6 working on the hosts. Having the CNI handing out ipv6 configs to the pods would be step 2 I guess.

I made an ubuntu server and added it to a hetzner-network created via this project, and it got an ipv6 addr+gateway so we can rule private networks being a problem out.

So after some digging on the agents themselves, I noticed the existence of the file `/etc/systemd/network/10-cloud-init-eth0.network`. But this is a configuration file for the `systemd-networkd` service, while the micro-os image runs the `NetworkManager` service for its network management.

If I take the file `/etc/systemd/network/10-cloud-init-eth0.network`, copy+convert it to `/etc/NetworkManager/system-connections/public_connection`, reboot and then ipv6 is working on the server 😄 Note that this file doesn't exist yet.

My next question is, who initializes the `10-cloud-init-eth0.network` file? is this from Hetzner, as it contains the static ipv6 address? This is the same address I see in the web-gui/console. And what would it take to let it configure the ipv6 for NetworkManager instead?

The reason why ipv4 works without this file is probably it defaults to DHCP on all connections, and for ipv4 it returns the configured ipv4 addr. ipv6 dhcp is probably disabled, but the docs aren't very clear on it in my experience. enabling ipv6 via DHCP results in a not booting VM.

Existing `/etc/systemd/network/10-cloud-init-eth0.network` file on host
```ini
[Address]
Address=2a01:4f8:1c1c:f547::1/64

[Match]
MACAddress=96:00:02:24:f6:00
Name=eth0

[Network]
DHCP=ipv4
DNS=2a01:4ff:ff00::add:1 2a01:4ff:ff00::add:2

[Route]
Gateway=fe80::1
```

Created and converted `/etc/NetworkManager/system-connections/public_connection`. note it should be chmod 600 and owned by root before it gets picked up.
```ini
[connection]
id=public_connection
type=ethernet
autoconnect=true

[ipv4]
method=auto

[ipv6]
method=manual
addresses=2a01:4f8:1c1c:f547::1/64
gateway=fe80::1

[ethernet]
mac-address=96:00:02:24:f6:00
```

Results ping6 after config and reboot. Containers not working yet
```bash
k3s-test-control-plane-fsn1-mbd:~ # ping -6 google.com
PING google.com(fra24s08-in-x0e.1e100.net (2a00:1450:4001:82b::200e)) 56 data bytes
64 bytes from fra24s08-in-x0e.1e100.net (2a00:1450:4001:82b::200e): icmp_seq=1 ttl=57 time=3.93 ms
64 bytes from fra24s08-in-x0e.1e100.net (2a00:1450:4001:82b::200e): icmp_seq=2 ttl=57 time=4.15 ms
64 bytes from fra24s08-in-x0e.1e100.net (2a00:1450:4001:82b::200e): icmp_seq=3 ttl=57 time=3.72 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 3.721/3.933/4.149/0.174 ms
```

**Comment by ifeulner** [comment] 2023-04-30 14:13
it would be great to have finally a IPv6 only cluster setup, but it needs thorough testing especially as there seem to be some issues in k3s with older kubernetes versions: see https://docs.k3s.io/installation/network-options

**Comment by riemervdzee** [comment] 2023-04-30 14:40
There are a lot of moving pieces indeed 😅 , and I myself am learning as I go forward. Pod to Pod communications, the k8s subnet and etc. can still be IPv4 in my opinion, otherwise, the rabbit hole goes too deep and I don't want to bring myself, or you guys, into that.

But to clarify my personal objective, and I am unsure whether this is possible but; I hope that the Pod can, via the node, access External resources via IPv6. 

To come back to the original problem; My workloads use CloudFlare R2 buckets to upload data, and 1 in 30 DNS queries result in an IPv6 address. In the current situation, with no IPv6 route toward them, the access to these buckets fails 3% of the time.

Configuring coredns to return IPv4 addresses is also a pain, as k3s resets the config-map to its original on reboot. At the moment I fixed it with the following, but it requires overriding every External host...

```yaml
apiVersion: v1
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  youtube.server: |
    youtube.com {
      forward . /etc/resolv.conf
      rewrite stop type AAAA A
      cache 600
    }

**Comment by mysticaltech** [comment] 2023-05-01 07:25
@riemervdzee Great debugging! The config happens through cloud-init, and we can definitely tweak this as we control the process (see cloud-init templates in the project).

However, the coredns comfig being rewritten on reboot can be solved. If coredns uses Rancher helmchart definitions (run kubectl get  helmchart), we can create a helmchartconfig definition with the permanent config, and it will ensure the config-map has the right values.

**Comment by mysticaltech** [comment] 2023-05-05 08:35
@riemervdzee Where you able to try modifying the coredns helmchart definition to fix the issue?

**Comment by riemervdzee** [comment] 2023-05-05 09:03
> @riemervdzee Where you able to try modifying the coredns helmchart definition to fix the issue?

No, not yet and I apologize for not responding earlier, busy days. But I'll have some time to look at it this weekend. 

I did some research and so far I read I have to disable coredns on k3s at the command-line, and then (re)install it via helm charts?

**Comment by mysticaltech** [comment] 2023-05-05 10:19
@riemervdzee My bad, coredns is not installed via helm charts, it's bundled inside the k3s binary. So I chatted a little bit with GPT4, it suggests you just create another configmap (by dumping the original one and modifying it like you did previously), create that one with another name, leaving the default one intact. Then edit the coredns deployment as to use that one instead. According to it, doing that it will not switch back to the old one when k3s upgrades. See the full conversation below-

----

# Installing CoreDNS in K3s

#### You:
How is coredns installed by k3s

#### ChatGPT:
K3s is a lightweight Kubernetes distribution developed by Rancher Labs. It is designed to be easy to install and configure, making it a popular choice for edge computing, IoT, and other resource-constrained environments.

CoreDNS is the default DNS server used by Kubernetes for service discovery. When you install K3s, it automatically deploys CoreDNS as a part of the control plane components.

Here's a brief overview of how CoreDNS is installed by K3s:

1. K3s bundles all the required components, including CoreDNS, in a single binary. This approach simplifies the installation process and reduces the overall footprint.

2. When you install K3s on a node, it sets up the Kubernetes control plane, which includes the API server, etcd, controller manager, and scheduler. As a part of this process, K3s deploys CoreDNS as a Kubernetes Deployment.

3. The CoreDNS Deployment is configured using a ConfigMap, which defines the Corefile (CoreDNS's configuration file). The ConfigMap allows users to customize the CoreDNS configuration as needed.

4. CoreDNS is exposed as a Kubernetes Service with a ClusterIP, enabling other components and applications within the cluster to access it using the Kubernetes DNS.

5. K3s configures the kubelet on each node to use the CoreDNS Service for DNS resolution. Pods running in the cluster can then resolve Kubernetes services and other domain names using the CoreDNS Service.

To check the status of CoreDNS in a K3s cluster, you can use the following command:

```
kubectl get pods -n kube-system -l k8s-app=kube-dns
```

This command will display the CoreDNS pods running in the `kube-system` namespace, along with their status.


#### You:
Ok. What is happening is that my networking stack does not support IPv6 but coredns sometimes gives IPv6 resolution when pods want to communicate with outside services. I managed to fix this with a coredns configmap forcing it to use only IPv4 resolutions, but when k3s gets upgraded, that configmap gets re-written. How to fix this?

#### ChatGPT:
When you upgrade K3s, it may overwrite the default configuration for some components, including the CoreDNS ConfigMap. To fix this issue and make your custom CoreDNS configuration persistent across upgrades, you can create a new ConfigMap with your custom configuration and modify the CoreDNS deployment to use the new ConfigMap. Here's how you can do this:

1. Save your custom CoreDNS configuration in a file, e.g., `custom-coredns-config.yaml`:

   ```
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: custom-coredns
     namespace: kube-system
   data:
     Corefile: |
       .:53 {
           errors
           health {
              lameduck 5s
           }
           ready
           kubernetes cluster.local in-addr.arpa ip6.arpa {
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
           }
           prometheus :9153
           forward . /etc/resolv.conf {
              max_concurrent 1000
              prefer_udp
              force_tcp
           }
           cache 30
           loop
           reload
           loadbalance
       }
   ```

   Customize the `Corefile` section as needed to enforce IPv4-only resolution.

2. Apply the custom ConfigMap:

   ```
   kubectl apply -f custom-coredns-config.yaml
   ```

3. Modify the CoreDNS deployment to use the new ConfigMap:

   ```
   kubectl -n kube-system patch deployment coredns --type json -p '[{"op": "replace", "path": "/spec/template/spec/volumes/0/configMap/name", "value": "custom-coredns"}]'
   ```

   This command patches the CoreDNS deployment, replacing the volume that references the original ConfigMap with the new custom ConfigMap.

4. The change in the deployment will cause the CoreDNS pods to restart. Verify that the new configuration is in use:

   ```
   kubectl get pods -n kube-system -l k8s-app=kube-dns
   ```

   Check the logs to ensure that CoreDNS is using the new configuration:

   ```
   kubectl logs -n kube-system -l k8s-app=kube-dns
   ```

By using a separate ConfigMap and updating the CoreDNS deployment to use it, your custom configuration should persist across K3s upgrades. Remember to monitor and update your custom configuration as needed to stay compatible with future CoreDNS and K3s releases.

**Comment by mysticaltech** [comment] 2023-05-05 11:17
@riemervdzee FYI the issue is a k3s one https://github.com/k3s-io/k3s/discussions/5993.

Also, another quick work around would be to set a pod dnsPolicy according to https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/.

**Comment by riemervdzee** [comment] 2023-05-05 12:34
@mysticaltech Hehe nice, I will have a crack at it tomorrow!

**Comment by mysticaltech** [comment] 2023-05-06 03:35
@riemervdzee One of k3s's maintainers replied, and he basically said that to block at the kube level is not the right way, and that we should disable IPv6 on the node itself. If you can SSH into one of your nodes and investigate this it would be super awesome. If that's really the case, we will just disable it during cloud-init and problem should be solved. 

See his comment here https://github.com/k3s-io/k3s/discussions/5993#discussioncomment-5819119.

**Comment by riemervdzee** [comment] 2023-05-06 07:53
@mysticaltech Sure, this was the first thing I tried, but I should have included that in this thread. 
I now have disabled IPv6 on the interface level by adding the following to `locals.tf` and recreating the test cluster:

``` terraform
- content: |
    net.ipv6.conf.all.disable_ipv6 = 1
    net.ipv6.conf.default.disable_ipv6 = 1
    net.ipv6.conf.lo.disable_ipv6 = 1
    net.ipv6.conf.eth0.disable_ipv6=1
    net.ipv6.conf.eth1.disable_ipv6=1
  path: /etc/sysctl.d/10-disable-ipv6.conf
```

This successfully disables IPv6 on the node:

<img width="878" alt="Screenshot 2023-05-06 at 09 47 47" src="https://user-images.githubusercontent.com/510299/236610943-9e654928-4f02-4eaf-8b5c-e1bd877fdd91.png">


But when logged in into a pod I still have an IPv6 address (fe80-like), and when I do a `nslookup` in a pod I can still get IPv6 info:

<img width="635" alt="Screenshot 2023-05-06 at 09 29 45" src="https://user-images.githubusercontent.com/510299/236609909-2fc9b530-f9cc-426d-8771-a8f87cd4d561.png">

So this disables sending and receiving IPv6 on the link level, but it doesn't prevent DNS queries to get info about IPv6? 
Is there another way to disable IPv6? For this to work I think the Pod themselves shouldn't get a local IPv6 either, I guess we have to disable IPv6 on the kernel level? 

I will try to dig into how NodeJS is handling DNS queries/dual stack, atm this is the biggest offender in my production cluster

**Comment by riemervdzee** [comment] 2023-05-06 17:17
Unfortunately, I couldn't make much progress on disabling IPv6 fully or find out why IPv6 addresses are returned at all. With IPv6 disabled on the host, the pod still gets a `fe80::` address and still thinks it's ok to sometimes connect via IPv6 it seems... Note I haven't tried copying the CoreDNS config or the dnsPolicy yet btw.

But I found out today why cloud-init doesn't generate a NetworkManager configuration file. Cloud-init tests the existence of some files and binaries, and testing file `/etc/NetworkManager/NetworkManager.conf` fails. https://github.com/canonical/cloud-init/blob/main/cloudinit/net/network_manager.py#L381

If I create this file (via `touch`) in the `hcloud-microos-snapshots.pkr.hcl` packager for example, the node at least starts up with full IPv6 support. It needs to exist pretty early while booting, maybe there is a better place to create this file though.

Unfortunately, this doesn't bring IPv6 routes to the Pods. Maybe I am a bit stubborn, and failing to disable ipv6 probably had something to do with this, but I feel IPv6 support should be the right way to go? 😅 I think I will test the CoreDNS config trick tomorrow though

**Comment by aleksasiriski** [comment] 2023-05-06 17:26
IPv6 should definitely be supported, when I get the time I'll try to help but idk when. Great work so far!

**Comment by mysticaltech** [comment] 2023-05-06 21:43
@riemervdzee Indeed superb breakthroughs. So basically, we can touch that network manager file in the pkr file, no problem. For ipv4 we already set the route manually in cloud-config, so we can do the same for IPv6, please try:

sudo ip -6 route add default via fe80::1 dev eth0

Found the IPv6 gateway address from the Hetzner docs [here](https://docs.hetzner.com/cloud/servers/static-configuration/).

If that works, a PR is most welcome! 🚀

**Comment by riemervdzee** [comment] 2023-05-07 21:09
I've created a PR at https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/pull/792

Further configuration isn't required, as NetworkManager his new configfile has the IPv6 gateway in it 😄

**Comment by mysticaltech** [comment] 2023-05-08 21:35
Thank you for your contribution @riemervdzee, really appreciated! 🙏 It's been released in v2.1.6.

**Comment by mysticaltech** [comment] 2023-05-12 12:35
Apologies, I thought this was all working now. We can continue here!

**Comment by mysticaltech** [comment] 2023-05-13 02:23
@riemervdzee My understanding is that now we have potential outbound (via the node's IPv6) and inbound (via the LB) traffic working correctly. 

Why would we need to enable IPv6 at the cluster level? I see no benefit to that, especially that if I am not mistaken the Hetzner private network does not support it. 

So from my limited standpoint, there would be no benefit to support it, or am I missing something?

**Comment by mysticaltech** [comment] 2023-05-24 21:02
@riemervdzee Any comments on the above statement, I genuinely curious. I fail to understand the remaining lack of feature here.

**Comment by mysticaltech** [comment] 2023-05-24 21:07
If it's just cluster wide IPv6, my question would be why? Why would we need that, isn't the value of IPv6 mainly obvious for WANs only?

**Comment by mysticaltech** [comment] 2023-05-24 21:11
Also according to https://docs.hetzner.com/cloud/networks/server-configuration/, it seems that Hetzner private network that we use only supports IPv4.

I am closing this for now, but we can re-open if needed, no worries!

**Closed by mysticaltech** 2023-05-24 21:11 UTC
Labels: help wanted

**Comment by TroyKomodo** [comment] 2023-06-19 05:00
I think support of ipv6 at cluster level us useful if you want pods to connect to servers which support ipv6 only or connect to ipv6 only addresses.

**Comment by TroyKomodo** [comment] 2023-06-19 15:49
Inside the pods we only have a ipv4 address and no route for ipv6, am I missing something my understanding was if you wanted pods to work with ipv6 addresses you needed to provide an ipv6 address in dual stack from the cluster?
